# Generated by Django 4.2.1 on 2023-05-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listDiolog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyTitle', models.CharField(max_length=100, verbose_name='Titulo da Obra')),
                ('keywordVideo', models.FileField(upload_to='static/', verbose_name='Arquivo de video')),
                ('keywordName', models.CharField(max_length=50, verbose_name='Comando')),
                ('keywordNarrative', models.FileField(upload_to='static/', verbose_name='Arquivo de audio OGG')),
                ('keywordSpeech', models.TextField(verbose_name='Instruções de Sequência')),
            ],
            options={
                'verbose_name': 'IdaQr Dado',
                'verbose_name_plural': 'IdaQr Dados',
            },
        ),
    ]
