# Generated by Django 4.2.1 on 2023-05-12 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ida_dialog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=100, verbose_name='Obra: ')),
                ('comando_positivo', models.CharField(max_length=50, verbose_name='Comando Positivo: ')),
                ('comando_negativo', models.CharField(max_length=50, verbose_name='Comando Negativo: ')),
                ('audio', models.FileField(upload_to='static/', verbose_name='Arquivo de audio OGG')),
                ('video', models.FileField(upload_to='static/', verbose_name='Arquivo de video')),
            ],
            options={
                'verbose_name': 'IdaQr Obra',
                'verbose_name_plural': 'IdaQr Obras',
            },
        ),
        migrations.CreateModel(
            name='idaSubComandos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_comando', models.CharField(max_length=50)),
                ('audio', models.FileField(upload_to='static/', verbose_name='Arquivo de audio OGG subcomando')),
                ('descricoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ida_dialog.idaobra')),
            ],
            options={
                'verbose_name': 'IdaQr Subcomando',
                'verbose_name_plural': 'IdaQr Subcomandos',
            },
        ),
    ]
