# Generated by Django 4.2.1 on 2023-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_dialog', '0003_idaobra_descricao_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idaobra',
            name='descricao_obra',
            field=models.TextField(default='.', verbose_name='Descrição da Obra'),
        ),
    ]
