# Generated by Django 4.2.1 on 2023-05-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_dialog', '0004_alter_idaobra_descricao_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='idaobra',
            name='palavra_chave',
            field=models.CharField(default='Palavra Chave', max_length=50, verbose_name='Palavra chave da pesquisa: '),
        ),
    ]
