# Generated by Django 4.2.1 on 2023-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idaStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleSound', models.CharField(default='Titulo', max_length=50, verbose_name='Titulo da Entrada')),
                ('startSound', models.FileField(upload_to='static/', verbose_name='Audio tela inicial')),
            ],
            options={
                'verbose_name': 'IdaQr Inicio',
                'verbose_name_plural': 'IdaQr Inicio',
            },
        ),
    ]
