# Generated by Django 4.2.1 on 2023-05-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idastart',
            options={'verbose_name': 'IdaQr Inicio', 'verbose_name_plural': 'IdaQr Inicio'},
        ),
        migrations.AlterField(
            model_name='idastart',
            name='startSound',
            field=models.FileField(upload_to='static/', verbose_name='Audio tela inicial'),
        ),
    ]
