# Generated by Django 4.2.1 on 2023-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_start', '0002_alter_idastart_options_alter_idastart_startsound'),
    ]

    operations = [
        migrations.AddField(
            model_name='idastart',
            name='titleSound',
            field=models.CharField(default=' ', max_length=50, verbose_name='Titulo da Entrada'),
        ),
    ]
