# Generated by Django 4.2.1 on 2023-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida_start', '0003_idastart_titlesound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idastart',
            name='titleSound',
            field=models.CharField(default='Titulo', max_length=50, verbose_name='Titulo da Entrada'),
        ),
    ]
